### PR TITLE
Don't modify /sbin/init on the build host.

### LINKED ISSUE #472: When using `AGENT_INIT="yes" ./rootfs.sh centos` to build rootfs, kata-agent will be installed as init process on the build-host machine
# Description of problem

When using `AGENT_INIT="yes" ./rootfs.sh centos` to build rootfs, kata-agent will be installed as init process on the build-host machine

# Expected result

It should install `kata-agent` as init process to `rootfs-Centos/sbin/init` only:
```shell
[root@LIN-9756F85AB47 rootfs-builder]# pwd
/media/A/gopath/src/github.com/kata-containers/osbuilder/rootfs-builder
[root@LIN-9756F85AB47 rootfs-builder]# ll
总用量 72
drwxr-xr-x  2 root  4096 7月   1 17:42 alpine
drwxr-xr-x  2 root  4096 7月   3 20:01 centos
drwxr-xr-x  2 root  4096 7月   1 17:42 clearlinux
drwxr-xr-x  2 root  4096 7月   1 17:42 debian
drwxr-xr-x  2 root  4096 7月   1 17:42 euleros
drwxr-xr-x  2 root  4096 7月   1 17:42 fedora
-rw-r--r--  1 root  root   425 7月   4 10:40 kata-Centos-dnf.conf
-rw-r--r--  1 root  6913 7月   1 17:42 README.md
dr-xr-xr-x 17 root   root     4096 7月   4 10:43 rootfs-Centos
-rwxr-xr-x  1 root 17608 7月   4 10:36 rootfs.sh
drwxr-xr-x  2 root  4096 7月   1 17:42 suse
drwxr-xr-x  2 root  4096 7月   1 17:42 template
drwxr-xr-x  2 root  4096 7月   1 17:42 ubuntu
[root@LIN-9756F85AB47 rootfs-builder]#
```
```shell
[root@LIN-9756F85AB47 rootfs-builder]# AGENT_INIT="yes" ./rootfs.sh centos
[root@LIN-9756F85AB47 rootfs-builder]# ls -al rootfs-Centos/sbin/init 
-rwxr-xr-x 1 root root 28589112 7月   4 10:43 rootfs-Centos/sbin/init
[root@LIN-9756F85AB47 rootfs-builder]# ls -al /sbin/init
lrwxrwxrwx 1 root root 22 7月   3 18:50 /sbin/init -> ../lib/systemd/systemd
```
# Actual result
But after `AGENT_INIT="yes" ./rootfs.sh centos`, the result is:
```shell
[root@LIN-9756F85AB47 rootfs-builder]# AGENT_INIT="yes" ./rootfs.sh centos
[root@LIN-9756F85AB47 rootfs-builder]# ls -al rootfs-Centos/sbin/init 
-rwxr-xr-x 1 root root 28589112 7月   4 10:43 rootfs-Centos/sbin/init
[root@LIN-9756F85AB47 rootfs-builder]# ls -al /sbin/init
-rwxr-xr-x 1 root root 28589112 7月   4 10:43 /sbin/init
```
# How to repair
Here is the way to repair,just need to modify `rootfs.sh`:
```shell
main()
{
    parse_arguments $*
    check_env_variables
    
-   init="${ROOTFS_DIR}/sbin/init"                                                                                                                            

    if [ -n "$distro" ]; then
        build_rootfs_distro
    else
        #Make sure ROOTFS_DIR is set correctly
        [ -d "${ROOTFS_DIR}" ] || die "Invalid rootfs directory: '$ROOTFS_DIR'"

        # Set the distro for dracut build method
        detect_host_distro
        prepare_overlay
    fi

+   init="${ROOTFS_DIR}/sbin/init"
    setup_rootfs
}
```
I will submit this revision later

### PR DESCRIPTION
**Pull request by liangxianlong**
Don't modify `/sbin/init` on the host when using command `AGENT_INIT="yes" ./rootfs.sh centos` to build rootfs.
Fixes #472

Signed-off-by: liangxianlong <liang.xianlong@zte.com.cn>

### CODE REVIEW

**Comment by devimc** [comment]
CI is not happy, you need to specify a subsystem in the subject and a body, please take a look to these examples https://github.com/kata-containers/community/blob/master/CONTRIBUTING.md#examples

```
Found 1 commit between commit bf95484c9220367e82a996fcb3746577efcbc41c and branch master

ERROR: Commit bf95484c9220367e82a996fcb3746577efcbc41c: Failed to find subsystem in subject: "Don't modify `/sbin/init` on the host when using command `AGENT_INIT=\"yes\" ./rootfs.sh centos` to build rootfs."

ERROR: checkcommits failed. See the document below for help on formatting
```

**Comment by liangxianlong** [comment]
@devimc thinks, I will modify the commit as soon as possible.

**Comment by liangxianlong** [comment]
@devimc thinks, i will modify this commit as soon as posible.

**Pull request closed without merging**
