### PR TITLE
tests: Update kata-manager command

### LINKED ISSUE #113: Update the bats test to install docker using the kata manager
The kata manager script is being updated to add an explicit option to install docker, so update the bats test to make use of it since `kata-manager.sh install-packages` will soon *only* install the packages (no docker).

See:

- https://github.com/kata-containers/tests/pull/391
- https://github.com/kata-containers/documentation/pull/145

### PR DESCRIPTION
**Pull request by jodh-intel**
The `kata-manger.sh` utility is changing its behaviour so that
`install-packages` *only* installs packages (no container manager).
Update the command to both install Docker and the packages.

Fixes #113.

Signed-off-by: James O. D. Hunt <james.o.hunt@intel.com>

### CODE REVIEW

**Comment by jodh-intel** [comment]
This PR should not land until the following two have been merged:

- https://github.com/kata-containers/tests/pull/391
- https://github.com/kata-containers/documentation/pull/145

**Comment by jcvenegas** [comment]
@jodh-intel  now that both deps are merged do we need to rerun this PR? or still missing something else?

**Comment by jodh-intel** [comment]
Re-pushed. Let's see what the CI makes of it...

**Comment by jodh-intel** [comment]
Ever since we switched Jenkins backends, the osbuilder tests have been failing.

@chavafg - since this is a [`bats`](https://github.com/sstephenson/bats) test, I think it's probably due to erroneous output to `stdout`. Looking at the logs, I'd guess at one or both of the following being the cause as I don't recall seeing those on the old Jenkins system:

```
# dpkg-preconfigure: unable to re-open stdin: 
# sudo: unable to resolve host ubuntu-1604-168
```

I've checked the above `sudo` output and it is being sent to `stdout` so that atleast would cause a failure fwics.

**Comment by chavafg** [comment]
@jodh-intel I have added the `hostname` of the machines to the `/etc/hosts` and now the `sudo: unable to resolve host` issue no longer appears. But the tests keep failing. Investigating more.

**Comment by jcvenegas** [comment]
any update on this?

**Comment by jodh-intel** [comment]
Hi @jcvenegas - I've converted the bats script into a shell script and it works fine.

Considering how many commands are getting called by the bats tests and the awkwardness of bats itself (particularly debugging these weird failures), I'm actually wondering if we could consider converting the test to a `set -e` script. fwics, all bats is really doing for us is making it difficult to debug these failures... and printing pretty test results.

**Comment by jodh-intel** [comment]
1-line change waiting for an ack folk.... :smile:

**Comment by jodh-intel** [comment]
OMG the CI passed! :smile:

/me waits for reviews...

**Comment by jodh-intel** [comment]
Hi @devimc - could you tal? :)

**Comment by devimc** [comment]
lgtm

**Pull request merged**
