### PR TITLE
Add s390x architecture

### PR DESCRIPTION
**Pull request by alicefr**
This PR adds s390x architecture.

Co-authored-by: Yash D Jain <ydjainopensource@gmail.com>
Signed-off-by: Alice Frosi <afrosi@de.ibm.com>

### CODE REVIEW

**Comment by marcov** [comment]
Tests are not starting :sweat_smile: Another try...
/test

**Comment by marcov** [comment]
Nevermind, Jenkins is down.

@alicefr you may consider updating [this table](https://github.com/kata-containers/osbuilder#platform-distro-compatibility-matrix) to better track what are the arch/distros supported (can also be with another PR).

**Comment by jodh-intel** [comment]
Good catch @marcov - I think updating that table on this PR makes sense.

**Comment by alicefr** [comment]
@marcov @jodh-intel thanks for the suggestion. I was thinking to update it when the `s390x` port is complete. But I can do it now if you prefear.

**Comment by jodh-intel** [comment]
@alicefr - ok, let's do it that way. I've raised #198 for you to handle the doc update later.

**Pull request merged**
