### PR TITLE
Add kmod package

### PR DESCRIPTION
**Pull request by devimc**
Add kmod package for loading kernel modules

### CODE REVIEW

**Comment by grahamwhaley** [comment]
@Pennyzct ARM CI failed - looks like it could be related?
```
/home/jenkins/workspace/kata-containers-osbuilder-ARM-18.04-PR/go/src/github.com/kata-containers/agent /
rm -f kata-agent kata-agent.service
go build -buildmode=pie -tags "" -o kata-agent \
	-ldflags "-X main.version=1.9.0-alpha0-94e2a254a94a77c02280f4f84d7f82269be163ce -X main.seccompSupport=no "
install -D kata-agent /rootfs/usr/bin/kata-agent
Makefile:100: recipe for target 'install' failed
Failed at 497: make install DESTDIR="${ROOTFS_DIR}" INIT=${AGENT_INIT} SECCOMP=${SECCOMP}
Makefile:85: recipe for target '/tmp/osbuilder-test.20mpTCg/rootfs-osbuilder/.debian_rootfs.done' failed
make: *** [/tmp/osbuilder-test.20mpTCg/rootfs-osbuilder/.debian_rootfs.done] Error 2
make: *** Waiting for unfinished jobs....
INFO: Background rootfs build job failed:
```

**Comment by Pennyzct** [comment]
Hi @grahamwhaley It also confuses me😢. I'll rebuild to see if it's reproducible. If it is, I will dig it up. ;)

**Comment by marcov** [comment]
@grahamwhaley @Pennyzct The build timeout is triggered, likely because some time ago we reduced the amount of logs printed during tests.
Could the timeout be increased maybe?
```
Build timed out (after 10 minutes). Marking the build as aborted.
Build was aborted
Performing Post build task...
```

**Comment by marcov** [comment]
About the previous failure, you can scroll up in the log to get the output. It seems that the `kata-agent` binary was found during install, maybe because of a build error?
```
+ info 'Build agent'
+ local 'msg=Build agent'
+ echo 'INFO: Build agent'
+ pushd /home/jenkins/workspace/kata-containers-osbuilder-ARM-18.04-PR/go/src/github.com/kata-containers/agent
+ '[' -n '' ']'
+ make clean
+ make INIT=no
+ make install DESTDIR=/rootfs INIT=no SECCOMP=
install: cannot stat 'kata-agent': No such file or directory
make: *** [install] Error 1
++ handle_error 497
++ local exit_code=2
++ local line_number=497
++ echo 'Failed at 497: make install DESTDIR="${ROOTFS_DIR}" INIT=${AGENT_INIT} SECCOMP=${SECCOMP}'
++ exit 2
++ error_handler
```

**Comment by devimc** [comment]
ARM CI is also failing here https://github.com/kata-containers/osbuilder/pull/340

**Pull request merged**
