### PR TITLE
makefile: fix makefile to find Dockerfile.template

### LINKED ISSUE #67: template/Makefile unable to find Dockerfile.template
make -f template/Makefile  ROOTFS_BASE_NAME=opensuse
<....>
sed \
	-e "s|@distro@|opensuse|g" \
	Dockerfile.template > "/home/nirmoy/devel/kata/osbuilder/rootfs-builder/opensuse"/Dockerfile.in
sed: can't read Dockerfile.template: No such file or directory

### PR DESCRIPTION
**Pull request by nirmoy**
Fixes #67.
Signed-off-by: Nirmoy Das <ndas@suse.de>

### CODE REVIEW

**Comment by jodh-intel** [comment]
Hi @nirmoy - thanks for raising this!

Travis is failing due to a timeout, but in fact there is an earlier failure if you view the raw log:

```
Running checkcommits version 0.0.1 (commit 78ca43baea8c6708a443fde0c8edea3a3928780c)
Detected TravisCI Environment
Found 1 commit between commit 48c727274095b4ee766b4dd93a1386721374ae69 and branch master
ERROR: Commit 6bad10b6837744a49141cc54eaf22e2b105d9b81: single-line "Signed-off-by" body not permitted
ERROR: checkcommits failed. See the document below for help on formatting
commits for the project.
```

Please could you add a "body" to your commit message and a "Fixes #XXX" comment (just raise a brief issue and reference that - it doesn't actually need to be assigned to you) at the end as shown here:

- https://github.com/kata-containers/community/blob/master/CONTRIBUTING.md#patch-format

**Comment by jodh-intel** [comment]
By the way, that "hidden" error from checkcommits should have immediately aborted the build - I've raised #66 to fix that.

**Comment by nirmoy** [comment]
Thanks James I added an issue and referred in my commit.

**Comment by jodh-intel** [comment]
Hi @nirmoy - could you just add a brief description of the change in the commit (below your summary line)? Once that's done,

lgtm.

**Comment by jodh-intel** [comment]
Hi @jcvenegas - could you review please?

**Comment by jcvenegas** [comment]
lgtm

**Pull request merged**
