### PR TITLE
README.md [WIP]

### PR DESCRIPTION
**Pull request by nitkon**
Test PR to see how CI goes on ppc64le

Fixes:  #233

Signed-off-by: Nitesh Konkar niteshkonkar@in.ibm.com

### CODE REVIEW

**Comment by nitkon** [comment]
I guess the osbuilder CI will fail for all other archs untill we have `http://download.opensuse.org/repositories/home:/katacontainers:/releases:/x86_64:/master/xUbuntu_16.04/` repositories for ppc64le/arm64/s390x etc 
cc @jcvenegas @Pennyzct @alicefr

**Comment by grahamwhaley** [comment]
For reference, the fail is not obvious from the logs:
```
INFO: Running unit tests for repo github.com/kata-containers/osbuilder
/home/jenkins/workspace/kata-containers-osbuilder-Power8-ubuntu-16-04-PR-initrd/go/src/github.com/kata-containers/osbuilder/tests/test_images.sh "centos"
Cloning into '/home/jenkins/workspace/kata-containers-osbuilder-Power8-ubuntu-16-04-PR-initrd/go/src/github.com/kata-containers/documentation'...
Warning: apt-key output should not be parsed (stdout is not a terminal)
gpg: no valid OpenPGP data found.
INFO: ERROR: test failed

INFO: no rootfs created
```

but, I suspect what is happening is the scripts are trying to pull the apt key from an arch specific repo on OBS, of which there are none for Power8 for instance, and hence the fail? You think @nitkon .
Yeah, either we see if there is a way around that (a fix/PR) for this repo for all non-OBS enabled arch's right now, or we go disable the power8 CI on this repo for now.

The other CIs seem to have failed due to network timeouts afaict btw.

**Comment by nitkon** [comment]
@grahamwhaley : Yes, you are right. Fail is because of the unavailability of other arch specific repo on OBS.
I think we should get the OBS packaging in place first and then we can enable osbuilder CI on P8.
Till then we can disable this P8 CI ...

**Comment by grahamwhaley** [comment]
Done. the power8 CI osbuilder job in jenkins now disabled (job still there, just not active).
When we are ready we should just be able to re-enable it on the jenkins master.
/cc @chavafg

**Comment by jodh-intel** [comment]
Any update on this @nitkon ?

**Comment by chavafg** [comment]
should we close this one @nitkon ?

**Comment by nitkon** [comment]
Yup

**Pull request closed without merging**
