### PR TITLE
test: Modify test_images script to handle FC

### LINKED ISSUE #248: Modify test images script for firecracker

### PR DESCRIPTION
**Pull request by GabyCT**
We need to modify this test in order to handle firecracker.

Fixes #248

Signed-off-by: Gabriela Cervantes <gabriela.cervantes.tellez@intel.com>

### CODE REVIEW

**Comment by GabyCT** [comment]
The ci of FC is failing
```
+ built_images["${d}"]=342259838:536870912
+ info 'Creating container for centos'
+ s='Creating container for centos'
+ echo -e 'INFO: Creating container for centos\n'
INFO: Creating container for centos

+ install_image_create_container /tmp/osbuilder-test.1elKYVj/images/kata-containers-image-centos.img
+ local file=/tmp/osbuilder-test.1elKYVj/images/kata-containers-image-centos.img
+ '[' -z /tmp/osbuilder-test.1elKYVj/images/kata-containers-image-centos.img ']'
+ '[' '!' -e /tmp/osbuilder-test.1elKYVj/images/kata-containers-image-centos.img ']'
+ '[' -n '' ']'
+ chronic /tmp/jenkins/workspace/kata-containers-osbuilder-centos-7-4-firecracker-PR/go/src/github.com/kata-containers/osbuilder/tests/../../tests/cmd/kata-manager/kata-manager.sh reset-config
+ chronic /tmp/jenkins/workspace/kata-containers-osbuilder-centos-7-4-firecracker-PR/go/src/github.com/kata-containers/osbuilder/tests/../../tests/cmd/kata-manager/kata-manager.sh configure-image /tmp/osbuilder-test.1elKYVj/images/kata-containers-image-centos.img
+ create_container
++ mktemp
+ out=/tmp/tmp.MlP4m2foUm
+ local file=/proc/version
+ docker run --rm -i --runtime kata-runtime busybox cat /proc/version
Unable to find image 'busybox:latest' locally
latest: Pulling from library/busybox
697743189b6d: Pulling fs layer
697743189b6d: Verifying Checksum
697743189b6d: Download complete
697743189b6d: Pull complete
Digest: sha256:061ca9704a714ee3e8b80523ec720c64f6209ad3f97c0ff7cb9ec7d19f15149f
Status: Downloaded newer image for busybox:latest
docker: Error response from daemon: OCI runtime create failed: Failed to check if grpc server is working: context deadline exceeded: unknown.
+ exit_handler
+ '[' 125 -eq 0 ']'
+ exit_handler
+ '[' 125 -eq 0 ']'
+ info 'ERROR: test failed'
+ s='ERROR: test failed'
+ echo -e 'INFO: ERROR: test failed\n'
INFO: ERROR: test failed
```
I am not really familiar with the testing here at osbuilder, I see that the image that is failing is on centos is this related that FC is not working or any ideas why we can have this ? /cc @jodh-intel

**Comment by jodh-intel** [comment]
FC CI failing:

```
docker: Error response from daemon: OCI runtime create failed: Failed to check if grpc server is working: context deadline exceeded: unknown.
```

**Comment by GabyCT** [comment]
@jodh-intel , I remove the `depends-on` because I see that this tag does not work on this repository. The FC CI will not work until #247 is merged.

**Comment by GabyCT** [comment]
@jodh-intel , I did the modifications now the CI for FC is working

**Pull request merged**
