### PR TITLE
# Kata Containers 1.13.0-alpha1

### PR DESCRIPTION
**Pull request by bergwolf**
Version bump no changes

### CODE REVIEW

**Review by fidencio — APPROVED** [review]
lgtm, thanks @bergwolf!

**Review by egernst — APPROVED** [review]

**Comment by fidencio** [comment]
```
19:08:19 From https://github.com/kata-containers/tests
19:08:19  = [up to date]      main       -> origin/main
19:08:19 Running checkcommits version 0.0.1 (commit 8ae89aa3c93b7855de2c1b763e2528bc6fecce43)
19:08:19 ERROR: Failed to run command /usr/bin/git rev-list --no-merges --reverse origin/main..HEAD: exit status 128 (stdout: , stderr: fatal: ambiguous argument 'origin/main..HEAD': unknown revision or path not in the working tree.
19:08:19 Use '--' to separate paths from revisions, like this:
19:08:19 'git <command> [<revision>...] -- [<file>...]'
19:08:19 )
19:08:19 ERROR: checkcommits failed. See the document below for help on formatting
19:08:19 commits for the project.
19:08:19 
```

**Comment by fidencio** [comment]
We need to adjust the CI to fetch content from kata-containers/tests master repo, I guess.

**Comment by fidencio** [comment]
We're closing this one as we'll go directly to the 1.13.0-rc0.

**Pull request closed without merging**
