### PR TITLE
Dockerfile: remove arch-specific dockerfiles

### PR DESCRIPTION
**Pull request by Pennyzct**
Hi guys

I've invented aarch64-specific dockerfiles in https://github.com/kata-containers/osbuilder/pull/412, and it's causing problem, thanks @jodh-intel for pointing out in https://github.com/kata-containers/osbuilder/pull/449#pullrequestreview-400716563, that is, a few common improvements introduced to generic file have been missing in `Dockerfile-aarch64.in`.

The difference comes from how to install musl tool chains.
So, here, I'd like to remove arch-specific dockerfiles with simply let ubuntu/debian use the same musl installing method as other distros do.

Otherwise, I've found that CI only tested **ubuntu/clearlinux image in x86_64** and **ubuntu in aarch64**, due to time out issue https://github.com/kata-containers/osbuilder/issues/46. 
Since this issue has already been closed(got fixed, right?), we need to bring the other distros back. ;)

### CODE REVIEW

**Review by c3d — APPROVED** [review]
lgtm, but I could not investigate CI tests (it times out on me)

**Review by jodh-intel — APPROVED** [review]

**Comment by grahamwhaley** [comment]
@Pennyzct , Travis looked to time out as well:

```
before_script

34.98s$ .ci/setup.sh

$ travis_wait 50 .ci/run.sh

Still running (50 of 50): .ci/run.sh

The job exceeded the maximum time limit for jobs, and has been terminated.
```

**Comment by Pennyzct** [comment]
thanks @devimc @c3d @grahamwhaley @jodh-intel 
In my third commit, I've tried to bring more tests online. For now, we only test clearlinux and ubuntu images. 
And the reason could be traced back to this issue https://github.com/kata-containers/osbuilder/issues/46, but I see it has already been closed. Emmmmmm, maybe the problem is still out there???

**Comment by devimc** [comment]
@Pennyzct afaik, the issue with euleros is still there, no idea why that issue was closed

**Comment by fidencio** [comment]
Is this something we still need?  I'm about to cut the final 1.x release and I'd be okay to wait for this one to make its way in in the next few days.  Otherwise, let's close it here, check whether the same issue affects kata-containers 2.x, and open a new PR there.

Does this sound reasonable?

**Comment by fidencio** [comment]
Folks, this PR has been stale and I'm closing it as we're walking towards the **final** 1.13.0 release of the kata-containers-1.x.
From now on, all the development will happen as part of https://github.com/kata-containers/kata-containers/ and fixes should be provided to that repo.

Thanks a lot for your contribution, we're sorry that for some reason it got stale, and we hope to see you around for new adventures in the kata-containers-2.x land.

**Pull request closed without merging**
