### PR TITLE
Install the right golang binaries for ppc64le

### LINKED ISSUE #72: rootfs building on ppc64le is broken
Getting `exec format error` on ppc64le because golang binaries are downloaded for x86 by default. 

I will send the fix for this.

### PR DESCRIPTION
**Pull request by harche**
Install the right golang binaries for ppc64le

Fixes #72

Signed-off-by: Harshal Patil <harshal.patil@in.ibm.com>

### CODE REVIEW

**Comment by bergwolf** [comment]
@harche Please add submodule to the commit subject, something like `rootfs: fix xxx`. The commit subject format is required in all kata containers projects.

**Comment by jodh-intel** [comment]
Once the commit subsystem has been added (https://github.com/kata-containers/community/blob/master/CONTRIBUTING.md#patch-format)...

lgtm

**Comment by harche** [comment]
@jodh-intel done.

**Comment by jodh-intel** [comment]
Thanks @harche! Travis seems happier now...

**Pull request merged**
