### PR TITLE
Pass EXTRA_PKGS var to docker to build rootfs

### LINKED ISSUE #74: EXTRA_PKGS variable is not passed to rootfs build using docker
When rootfs is built using docker, EXTRA_PKGS variable described [here](https://github.com/kata-containers/osbuilder/tree/master/rootfs-builder#adding-extra-packages), doesn't get passed. 

This results in incorrect rootfs when it's built using docker and require to have extra packages using EXTRA_PKGS. 

I will send the fix for this.

### PR DESCRIPTION
**Pull request by harche**
Fixes #74

Signed-off-by: Harshal Patil <harshal.patil@in.ibm.com>

### CODE REVIEW

**Comment by jodh-intel** [comment]
Good catch @harche ! ;)

Again, please can you add a "subsystem" tag ("rootfs" would work well here) to your commit as described in https://github.com/kata-containers/community/blob/master/CONTRIBUTING.md#patch-format.

Once done,

lgtm.

**Comment by harche** [comment]
@jodh-intel done.

**Comment by jodh-intel** [comment]
Ta!

**Comment by devimc** [comment]
lgtm

**Pull request merged**
