### PR TITLE
skip euleros build due to timeout reason

### LINKED ISSUE #46: travis stop build when building euleros
Sometimes when euleros tests is being executed by travis, it stops all the ci because not output in more than 10 minutes.

See:

https://travis-ci.org/kata-containers/osbuilder/builds/333273461

### PR DESCRIPTION
**Pull request by liangchenye**
Fixes #46.

Signed-off-by: Liang Chenye <liangchenye@huawei.com>

### CODE REVIEW

**Comment by jcvenegas** [comment]
Hi, @liangchenye  we we still had sometimeouts due to not output given the travis timeout, could you try to edit the line 
https://github.com/kata-containers/osbuilder/blob/master/.travis.yml#L19

```yaml
script: 
- "travis_wait 30 .ci/run.sh"
```
Acording to travis docs that will increase the wait time to 30 min
https://docs.travis-ci.com/user/common-build-problems/#Build-times-out-because-no-output-was-received

**Comment by jodh-intel** [comment]
Random idea: you could try contacting https://www.mirrorservice.org/ (or some other mirroring site) and see if they would mirror euleros. They already mirror centos and scientific linux (centos based):

- https://www.mirrorservice.org/sites/

**Comment by liangchenye** [comment]
@jodh-intel I got feedback from the maintainer of 'mirrorservice.org', they prefer to host non-commercial product. So they mirror centos/opensuse and don't mirror RHEL/SLE.  
EulerOS is more like a 'commercial product', so I agree it is not suitable to mirror it there.

We do have a community brand 'iSula' which is a container OS, but it is quite new. (hopefully one day it will be  well-known.)

**Comment by liangchenye** [comment]
@jcvenegas the current server is not stable, I just afraid to break our CI.
I'm working with some guys in our company to solve it. It still need times.
I think we can just 'skip' the euleros build now.

**Comment by jodh-intel** [comment]
Hi @liangchenye - thanks for the update.

lgtm

**Comment by jcvenegas** [comment]
> So maybe I can close this PR?
@liangchenye sure we can close it, feel free to increase the time out as well if you think will need it in the future.

**Comment by jodh-intel** [comment]
Hi @liangchenye - do you plan to close this then, or do you want to rebase so we can merge it?

**Comment by liangchenye** [comment]
The build failed again，I'll rebase it. I'm on vacation，I‘ll do it the day after tomorrow.

**Comment by liangchenye** [comment]
rebased, PTAL @jodh-intel 

PS,
I built euleros locally by running `build_rootfs_image_initrd euleros`, it works.

**Comment by jodh-intel** [comment]
Thanks @liangchenye!

> I built euleros locally by running build_rootfs_image_initrd euleros, it works.

Great! :smile:

lgtm

**Comment by jodh-intel** [comment]
ping @kata-containers/builder

**Comment by jodh-intel** [comment]
Force merging since:

- we've waited long enough for this to be nacked.
- we need this to make the CI more stable...

**Pull request merged**
