### PR TITLE
rootfs: Default to host architecture

### LINKED ISSUE #100: Default architecture to host architecture
Currently the rootfs builder defaults to `x86_64` rather than the host architecture. This requires users to remember to override `ARCH` if they are building on a non-Intel platform which seems unnecessary.

### PR DESCRIPTION
**Pull request by jodh-intel**
Don't default to a hard-coded Intel architecture - default to the host
architecture.

Fixes #100.

Signed-off-by: James O. D. Hunt <james.o.hunt@intel.com>

### CODE REVIEW

**Comment by jodh-intel** [comment]
Hmm - something odd is happening here. Travis failed as I'd modified files that needed SPDX license headers. Adding those in a re-pushing... and Travis is no longer triggering...?!?

**Comment by jodh-intel** [comment]
I'd appreciate it if someone could independently review the authorship of the files I've added the SPDX license headers to, to ensure I've specified the correct copyright attribution.

**Comment by jodh-intel** [comment]
(bearing in mind that those files started out as `Dockerfile` and got converted to `Dockerfile.in` subsequently).

**Comment by grahamwhaley** [comment]
Those copyright assignments look like you have the right companies on the right files to me - but, yes, we should get an ack from each owner....
I ack the Intel ones, and you have sort of implicitly ack'd those already ;-)

**Comment by jodh-intel** [comment]
As @grahamwhaley established, for reasons currently unknown alpine doesn't provide an `arch` binary in the `coreutils` package.

I've cheated a bit by creating a shell alias to `uname -m` on alpine. But of course I could instead simply undo all the `arch(1)`-related changes on this PR. But that would undo all the SPDX goodness.

What say you @jcvenegas, @grahamwhaley?

**Comment by jodh-intel** [comment]
grrr. the alias didn't stick. I might just have to give up and use `uname -m` everywhere then ;(

**Comment by liangchenye** [comment]
Thanks @jodh-intel , I prefer to use this:
``` Copyright 2018 Huawei Technologies Co., Ltd```

**Comment by bergwolf** [comment]
lgtm

**Comment by jodh-intel** [comment]
Hi @liangchenye - thanks for responding. I've updated as you suggested but taken the liberty of adding in the standard `(C)` making it the following if that's ok with you?

```
Copyright (C) 2018 Huawei Technologies Co., Ltd
```

**Comment by liangchenye** [comment]
@jodh-intel it is ok to me, thanks for the correction.

**Comment by jodh-intel** [comment]
Thanks @liangchenye.

**Pull request merged**
