### PR TITLE
 suse: fix port URL detection for aarch64

### PR DESCRIPTION
**Pull request by marcov**
Fix port URL detection for aarch64, and error out if an unknown
architecture is detected.

Fixes: #215

### CODE REVIEW

**Comment by jodh-intel** [comment]
lgtm

/test

**Comment by devimc** [comment]
cc @Pennyzct @Weichen81

**Comment by Pennyzct** [comment]
I required `/test` here and it looks like that we didn't deploy arm CI under `kata-containers/osbuilder` repo?

**Comment by marcov** [comment]
You are right @Pennyzct, there are no ARM tests here. 

/cc @chavafg

**Comment by marcov** [comment]
There's something broken in the Fedora installation:
```
/tmp/jenkins/workspace/kata-containers-osbuilder-fedora-PR/go/src/github.com/kata-containers/tests/.ci/static-checks.sh: line 157: make: command not found
Build step 'Execute shell' marked build as failure
```

**Comment by jodh-intel** [comment]
@chavafg - another CI oddity today:

```
/tmp/jenkins/workspace/kata-containers-osbuilder-fedora-PR/go/src/github.com/kata-containers/tests/.ci/static-checks.sh: line 157: make: command not found
```

Same problem with the Fedora CI on #218.

**Comment by chavafg** [comment]
@jodh-intel This is the first time I see it here (when testing PRs), but I have actually seen this issue a lot in the job that runs the changes to the master branch. I'll open an issue to investigate this, but honestly not sure why this happens, I even tried adding a `dnf install make` at the beginning of the job and seems that it is not solving the issue.
e.g.

http://jenkins.katacontainers.io/job/kata-containers-osbuilder-fedora-master/48/console

**Pull request merged**
