### PR TITLE
travis: Enable travis ci for ppc64le

### PR DESCRIPTION
**Pull request by nitkon**
Fixes: #122

Signed-off-by: Nitesh Konkar <niteshkonkar@in.ibm.com>

### CODE REVIEW

**Comment by grahamwhaley** [comment]
May have been a big CI wobble - early curl issue on 16.04 at least - have nudged that one for a rebuild - let's see how it goes.

**Comment by jodh-intel** [comment]
Hi @nitkon - I've started to look at this, but am now rather confused. I see that you've duplicated the arm64 config file and updated for ppc64le. But all the centos variables below appear to be totally unused by osbuilder:

```
CENTOS_UPDATES_MIRROR_LIST
CENTOS_EXTRAS_MIRROR_LIST
CENTOS_PLUS_MIRROR_LIST
CENTOS_UPDATES_URL
CENTOS_EXTRAS_URL
CENTOS_PLUS_URL
```

/cc @Pennyzct, @jcvenegas.

**Comment by nitkon** [comment]
@jodh-intel : On removing these centos variables, the Travis-CI fails with the following [issue](https://github.com/kata-containers/osbuilder/issues/111)

**Comment by jcvenegas** [comment]
@jodh-intel  inteed just check and the variables are not used I crated an issue for that https://github.com/kata-containers/osbuilder/issues/138. That is not a blocker for this PR, I think.

**Comment by jodh-intel** [comment]
Thanks @jcvenegas.

lgtm.

**Comment by jodh-intel** [comment]
1 ack to go... ;)

**Pull request merged**
