### PR TITLE
# Kata Containers 1.2.0

### PR DESCRIPTION
**Pull request by jcvenegas**
- tests: Add ability to restrict which tests run
- rootfs.sh: Add Platform-OS matrix to help page
- initrd-builder: make initrd_builder.sh idempotent
- travis: Enable travis ci for ppc64le
- docs: Add Platform-Compatibility matrix
- rootfs: docker: Reduce build time by not reinstalling go
- CI: Install make on Ubuntu

c5e2c0f tests: Add more messages
9f2da28 docs: Updated for new test options
0cd64fb build: Added targets to run tests
0ea8ef7 tests: Rename test script
c679cae tests: Add ability to restrict which tests run
80e1997 tests: Create new function to launch tests
f077e6e tests: Rename distro test functions
adb3f57 rootfs.sh: Add Platform-OS matrix link to help page
1e5e915 docs: Add Platform-Compatibility matrix
25e9f01 rootfs: docker: Reduce build time by not reinstalling go
abb559d CI: Install make on Ubuntu
22f04db travis: Enable travis ci for ppc64le
a7bafc5 initrd-builder: make initrd_builder.sh idempotent

### CODE REVIEW

**Comment by jodh-intel** [comment]
lgtm

**Comment by devimc** [comment]
lgtm

**Comment by jcvenegas** [comment]
OBS  repos keeps failing in centos and fedora ... @jodh-intel @egernst @chavafg shall we ignore it?
``` 
Adding repo from: http://download.opensuse.org/repositories/home:/katacontainers:/release/Fedora_27/home:katacontainers:release.repo
Last metadata expiration check: 0:03:42 ago on Tue 07 Aug 2018 04:02:53 PM UTC.
No match for argument: kata-runtime
No match for argument: kata-proxy
No match for argument: kata-shim
INFO: ERROR: test failed
```

**Comment by grahamwhaley** [comment]
Can you tell/explain what is failing - is that failing to upload the results to OBS or build or ??? for instance - might help us decide if this is spurious or a longer term breakage - and if it is us or OBS ;-) thx

**Comment by chavafg** [comment]
I think we can ignore it, we did for another PR. We are still having issues with OBS availability. @grahamwhaley the failure occurs when trying to download the kata packages from OBS.

**Comment by grahamwhaley** [comment]
ack - np. Should be fun when we try to upload 1.2.0 then ;-)

**Comment by jcvenegas** [comment]
I created an issue to track it. 
https://github.com/kata-containers/packaging/issues/119

**Comment by grahamwhaley** [comment]
Given we are quite aware of the OBS issues, and have an Issue to track them, I'm going to merge this.

**Pull request merged**
