### PR TITLE
image-builder: fix "paratition" typo

### PR DESCRIPTION
**Pull request by stefanha**
Signed-off-by: Stefan Hajnoczi <stefanha@redhat.com>

### CODE REVIEW

**Comment by jodh-intel** [comment]
Hi @stefanha - Thanks for raising!

Travis has failed though due to your commit not having the required `Fixes #XXX` comment and a full commit body. See:

- https://github.com/kata-containers/community/blob/master/CONTRIBUTING.md#patch-format

However, I've just created #89 for you so if you change your commit to something like the following it will be happy :smile::

```
image-builder: fix "paratition" typo

Corrected a typo in the image builder script.

Fixes #89

Signed-off-by: Stefan Hajnoczi <stefanha@redhat.com>
```

**Comment by stefanha** [comment]
Thanks, I have pushed an updated commit and Travis has passed now.

**Comment by jodh-intel** [comment]
Thanks @stefanha!

lgtm

**Comment by jodh-intel** [comment]
ping @bergwolf, @grahamwhaley.

**Pull request merged**
