### PR TITLE
tests: Test generated images and initrd's (+ cleanups)

### LINKED ISSUE #97: Ensure images and initrds can boot a container
The CI tests don't currently test the resulting iimages and initrds.

Once https://github.com/kata-containers/documentation/issues/91 lands, we can:

- install kata from OBS using the script that PR provides.
- Configure the runtime to use the just-built image/initrd.
- Create a container.

### PR DESCRIPTION
**Pull request by jodh-intel**
After building the images, perform a very basic test by configuring the runtime to use them and creating a container.

Also a number of cleanups.

Fixes #97.
    
Signed-off-by: James O. D. Hunt <james.o.hunt@intel.com>

### CODE REVIEW

**Comment by grahamwhaley** [comment]
but, travis fails:
```
# INFO: Creating /tmp/osbuilder-test.xs4CdeN/images/initrd-alpine-agent-init-yes.img based on rootfs at /tmp/osbuilder-test.xs4CdeN/rootfs-osbuilder/alpine-agent-init-no
# 52863 blocks
# file not found: /home/travis/build/kata-containers/osbuilder/tests/../../tests/cmd/kata-manager/kata-manager.sh at /usr/bin/chronic line 44.
```

**Comment by jcvenegas** [comment]
looks good ! lets add a jenkins job to see all works as expected

**Comment by jodh-intel** [comment]
Hi @jcvenegas, @grahamwhaley - Travis is now happy so we could land.

Note that we're sort of "soft-blocked" on https://github.com/kata-containers/ci/issues/28 since without that, this PR won't actually test the images+initrd's (since Travis doesn't provide VT-x).

**Comment by jodh-intel** [comment]
Blocked on https://github.com/kata-containers/tests/pull/369.

**Comment by jodh-intel** [comment]
@jcvenegas, @grahamwhaley - it works! Now that https://github.com/kata-containers/tests/pull/369 has landed, we can now test all images and initrd's osbuilder generates! :smile:

```
1..5
ok 1 Can create and run fedora image
ok 2 Can create and run clearlinux image
ok 3 Can create and run centos image
ok 4 Can create and run euleros image
ok 5 Can create and run alpine image
```

**Comment by jodh-intel** [comment]
Hi @devimc - could you take a look?

**Pull request merged**
