### PR TITLE
chrony-service: re-patch PR#265

### PR DESCRIPTION
**Pull request by Pennyzct**
commit 39370c2 has accidentally deleted the content in #265
Here, I just re-patch PR#265 on the latest master code.

Fixes: #338

Signed-off-by: Archana Shinde <archana.m.shinde@intel.com>
Signed-off-by: Penny Zheng <penny.zheng@arm.com>

### CODE REVIEW

**Comment by grahamwhaley** [comment]
Better check with @marcov that the original delete was not intentional (I think it was not... but... ;-) )

**Comment by Pennyzct** [comment]
@jodh-intel Ahhhhh, that explained why I spent the whole morning searching repo with chrome and couldn't find the commit. I really need to learn how to use `git` to do the search.

**Comment by jodh-intel** [comment]
@Pennyzct - yes, `git` is the best way. But there is a bit of indirection since you can't search for the PR number (although you can search for the issue ;)

What I generally do is:

- Run `git log -p` to show the commits *and* the changes.
- Search (using `/`) for one of the the lines that is removed (in red) - for example `chrony_systemd_service=`.
- Then, search backwards (using `?`) for `^commit ` to find the closest commit to that which should have the `Fixes #XXX` comment.

**Comment by Pennyzct** [comment]
travis on ppc64le timed out. 
```
$ .ci/setup.sh
$ travis_wait 50 .ci/run.sh


Still running (48 of 50): .ci/run.sh

The job exceeded the maximum time limit for jobs, and has been terminated.
```
any idea? @nitkon

**Comment by chavafg** [comment]
Weird that ARM job passed on #312, seems like it tested master instead of the PR?

**Comment by chavafg** [comment]
ohh, nevermind, the thing is that this workflow does not run the `docker check dmesg logs errors` test

**Comment by chavafg** [comment]
I've restarted the firecracker and travis job which timed out.

**Comment by amshinde** [comment]
Restarting travis

**Comment by nitkon** [comment]
@Pennyzct: Yes, observed this in other projects as well. For some reason, Travis ppc64le CI runs are timing out today.

**Comment by nitkon** [comment]
So it's all green now!

**Comment by marcov** [comment]
Thank you for the catch @Pennyzct. That was a rebasing mistake.

**Pull request merged**
