### PR TITLE
s390x: set CC for fedora

### PR DESCRIPTION
**Pull request by alicefr**
Fixes: #217

Signed-off-by: Alice Frosi <afrosi@de.ibm.com>

### CODE REVIEW

**Comment by jodh-intel** [comment]
lgtm

**Comment by marcov** [comment]
respinning failed jobs...
/test-failed

**Comment by marcov** [comment]
Fedora CI machine is broken (unrelated to this PR):
```
/tmp/jenkins/workspace/kata-containers-osbuilder-fedora-PR/go/src/github.com/kata-containers/tests/.ci/static-checks.sh: line 157: make: command not found
Build step 'Execute shell' marked build as failure
```

**Pull request merged**
