### PR TITLE
pod : optimization Some debian package manager tweaks

### PR DESCRIPTION
**Pull request by Rajpratik71**
By default, Ubuntu or Debian based "apt" or "apt-get" system installs recommended but not suggested packages .

By passing "--no-install-recommends" option, the user lets apt-get know not to consider recommended packages as a dependency to install.

This results in smaller downloads and installation of packages .

Refer to blog at [Ubuntu Blog](https://ubuntu.com/blog/we-reduced-our-docker-images-by-60-with-no-install-recommends) .

Fixes : #427 

Signed-off-by: Pratik Raj <rajpratik71@gmail.com>

### CODE REVIEW

**Comment by devimc** [comment]
thanks @Rajpratik71 please fix your commit message, https://github.com/kata-containers/community/blob/master/CONTRIBUTING.md#patch-format

**Comment by Rajpratik71** [comment]
> thanks @Rajpratik71 please fix your commit message, https://github.com/kata-containers/community/blob/master/CONTRIBUTING.md#patch-format

changed . take a look

**Comment by Rajpratik71** [comment]
@liwei @jbryce requesting review

**Comment by grahamwhaley** [comment]
Hi @Rajpratik71 - it is the commits that need the subject prefixes, not the PR itself. The CI is still kicking it out (you can check that by following the `details` links next to the CIs at the bottom of the PR on github)...

```
ERROR: Commit ffe6b3c22a8d9e101c0f715be686c6aa386e540a: Failed to find subsystem in subject: "Some debian package manager tweaks"

ERROR: checkcommits failed. See the document below for help on formatting

commits for the project.

https://github.com/kata-containers/community/blob/master/CONTRIBUTING.md#patch-format
```

**Comment by jodh-intel** [comment]
Thanks @Rajpratik71. The content looks good but as @grahamwhaley says, please update the commits so the first line shows a summary with a "subsystem". I'd recommend something like:

- first commit:
  ```
  debian: Don't install recommended software

  <existing text of the commit>
  ```

- second commit:
  ```
  debian: Install missing ca-certificates package

  <existing text of the commit>

  ```

You also need to raise a github issue (a couple of clicks ;) and reference that in atleast one of the commits by simply adding the following text to the commit:

```
Fixes: #issue_number
```

See the URL mentioned for full details.

**Comment by Rajpratik71** [comment]
> Thanks @Rajpratik71. The content looks good but as @grahamwhaley says, please update the commits so the first line shows a summary with a "subsystem". I'd recommend something like:
> 
> * first commit:
>   ```
>   debian: Don't install recommended software
>   
>   <existing text of the commit>
>   ```
> * second commit:
>   ```
>   debian: Install missing ca-certificates package
>   
>   <existing text of the commit>
>   ```
> 
> You also need to raise a github issue (a couple of clicks ;) and reference that in atleast one of the commits by simply adding the following text to the commit:
> 
> ```
> Fixes: #issue_number
> ```
> 
> See the URL mentioned for full details.

done as requested

**Pull request merged**
