### PR TITLE
rootfs.sh: Add Platform-OS matrix to help page

### PR DESCRIPTION
**Pull request by nitkon**
Fixes: #139

Signed-off-by: Nitesh Konkar <niteshkonkar@in.ibm.com>

### CODE REVIEW

**Comment by jodh-intel** [comment]
Hi @nitkon - thanks for raising but I'd rather we have a single place for defining that list of valid combinations. We now have that (https://github.com/kata-containers/osbuilder#platform-distro-compatibility-matrix) so rather than another copy, could you just reference that document?

**Comment by nitkon** [comment]
@jodh-intel : Should we remove this info
```
Supported Linux distributions:

clearlinux
fedora
centos
alpine
euleros
```
and replace it with
```
Refer the supported Platform-OS Compatibility Matrix: https://github.com/kata-containers/osbuilder#platform-distro-compatibility-matrix
```

**Comment by nitkon** [comment]
Updated my PR.

**Comment by jodh-intel** [comment]
Thanks @nitkon!

lgtm

**Comment by jcvenegas** [comment]
`curl: (56) GnuTLS recv error (-54): Error in the pull function.` network issue downloading golang. 
restarting ubuntu job.

**Pull request merged**
